name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run:  echo "${{secrets.DOCKER_TOKEN}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
      - name: build the docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/schoolleaver:latest

      - name: docker push
        run: docker push ${{secrets.DOCKER_USER}}/schoolleaver

